<?php
/**
 * @var string $fullName
 * @var string $email
 *
 */

?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="../assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="../assets/img/favicon.png">

  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />
  <!-- Nucleo Icons -->
  <link href="../assets/css/nucleo-icons.css" rel="stylesheet" />
  <link href="../assets/css/nucleo-svg.css" rel="stylesheet" />
  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
  <!-- Material Icons -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Round" rel="stylesheet">
  <!-- CSS Files -->
  <link id="pagestyle" href="../assets/css/material-dashboard.css?v=3.1.0" rel="stylesheet" />
  <!-- Nepcha Analytics (nepcha.com) -->
  <!-- Nepcha is a easy-to-use web analytics. No cookies and fully compliant with GDPR, CCPA and PECR. -->
  <script defer data-site="YOUR_DOMAIN_HERE" src="https://api.nepcha.com/js/nepcha-analytics.js"></script>
    <title>
        My Profile
    </title>
</head>

<body class="g-sidenav-show bg-gray-200">
    <?php
    include_once $_SERVER["DOCUMENT_ROOT"] . "/templates/layout/sidebar.phtml";
    ?>
  <div class="main-content position-relative max-height-vh-100 h-100">
    <!-- Navbar -->
        <?php
        include_once $_SERVER["DOCUMENT_ROOT"] . "/templates/layout/nav_bar.phtml";
        ?>
    <!-- End Navbar -->
      <div class="container-fluid px-2 px-md-4">
      <div class="page-header min-height-300 border-radius-xl mt-4" style="background-image: url('https://images.unsplash.com/photo-1531512073830-ba890ca4eba2?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1920&q=80');">
        <span class="mask  bg-gradient-primary  opacity-6"></span>
      </div>
      <div class="card card-body mx-3 mx-md-4 mt-n6">
        <div class="row gx-4 mb-2">
          <div class="col-auto">
            <!--<div class="avatar avatar-xl position-relative">
              <img src=" ../../assets/img/img_profile/<?php /*echo $pictureProfile*/?>" alt="profile_image" class="w-100 border-radius-lg shadow-sm">
            </div>-->
          </div>
          <div class="col-auto my-auto">
            <div class="h-100">
              <h5 class="mb-1">
                  <?=$fullName?>
              </h5>
              <p class="mb-0 font-weight-normal text-sm">
                CEO / Co-Founder
              </p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="row">
                <div class="col-12 col-xl-4">
                  <div class="card card-plain h-100">
                    <div class="card-header pb-0 p-3">
                      <div class="row">
                        <div class="col-md-8 d-flex align-items-center">
                          <h6 class="mb-0">Profile Information</h6>
                        </div>
                        <div class="col-md-4 text-end">
                          <a href="javascript:;">
                            <button class="fas fa-user-edit text-secondary text-sm" data-bs-toggle="tooltip" data-bs-placement="top" title="Edit Profile" id="editProfileBtn"></button>
                          </a>
                        </div>
                      </div>
                    </div>
                    <div class="card-body p-3">
                        <form role="form">
                            <div class="input-group input-group-outline mb-3">
                                <label class="col-form-label">Name</label>&nbsp;
                                <input type="text" class="form-control" value="<?php echo $fullName;?>" readonly>
                            </div>
                            <div class="input-group input-group-outline mb-3">
                                <label class="col-form-label">Email</label>&nbsp;
                                <input type="email" class="form-control" value="<?php echo $email; ?>" readonly>
                            </div>
                        </form>
                    </div>
                  </div>
                </div>
                <div class="col-12 col-xl-4">
                <div class="card-body pb-0 ">
              <div class="col-md-8 d-flex align-items-center">
                  <h6 class="mb-0">Change Password</h6>
              </div>
              <div class="card-body p-3">
              <form role="form">
                  <div class="input-group input-group-outline mb-3">
                      <label class="col-form-label">Current Password</label>&nbsp;
                      <input type="password" class="form-control" value="<?php echo $password; ?>" readonly>
                  </div>
                  <div class="input-group input-group-outline mb-3">
                      <label class="col-form-label">New Password</label>&nbsp;
                      <input type="password" class="form-control" value="<?php echo $password; ?>" >
                  </div>
              </form>
              </div>
                </div>
                </div>

      <?php
      include_once include_once $_SERVER["DOCUMENT_ROOT"] ."/templates/layout/footer.phtml"
      ?>
  </div>

  <!--   Core JS Files   -->
  <script src="../assets/js/core/popper.min.js"></script>
  <script src="../assets/js/core/bootstrap.min.js"></script>
  <script src="../assets/js/plugins/perfect-scrollbar.min.js"></script>
  <script src="../assets/js/plugins/smooth-scrollbar.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script>
        var win = navigator.platform.indexOf('Win') > -1;
        if (win && document.querySelector('#sidenav-scrollbar')) {
            var options = {
                damping: '0.5'
            }
            Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
        }
    </script>
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <script src="../assets/js/material-dashboard.min.js?v=3.1.0"></script>
    <script>
            $(document).ready(function() {
            $('#editProfileBtn').on('click', function() {
                // Toggle the disabled attribute for the input fields
                $('[name="fullName"] ').prop('disabled', function(i, val) {
                    return !val;
                });
                $('[name="email"]').prop('disabled', function(i, val) {
                    return !val;
                });
                $('[name="location"]').prop('disabled', function(i, val) {
                    return !val;
                });
                $('p.text-sm').attr('contenteditable', function(i, val) {
                    return val === 'true' ? 'false' : 'true';
                });
                // Change the button text and behavior
                let icon = $(this).find('i');
                if (icon.hasClass('fa-user-edit')) {
                    icon.removeClass('fa-user-edit').addClass('fa-save');
                } else {
                    icon.removeClass('fa-save').addClass('fa-user-edit');
                }
            });
        });
    </script>
</body>
</html>