<!DOCTYPE html>
<html lang="en">
<head>
    <?php
    include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/header.phtml';
    ?>
    <title>My Profile</title>
</head>
<body class="nav-fixed">
<?php
include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/navbar.phtml';
?>
<div id="layoutSidenav">
    <?php
    include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/sidebar.phtml';
    ?>
    <div id="layoutSidenav_content">
        <main>
            <header class="page-header page-header-compact page-header-light border-bottom bg-white mb-4">
                <div class="container-fluid px-4">
                    <div class="page-header-content">
                        <div class="row align-items-center justify-content-between pt-3">
                            <div class="col-auto mb-3">
                                <h1 class="page-header-title">
                                    <div class="page-header-icon"><i data-feather="user"></i></div>
                                    My Profile
                                </h1>
                            </div>
                        </div>
                    </div>
                </div>
            </header>
            <!-- Main page content-->
            <div class="container-fluid px-4 mt-4">
                <div class="row">
                    <div class="col-xl-6">
                        <!-- Account details card-->
                        <div class="card">
                            <div class="card-header text-center">Account Details</div>
                            <div class="card-body">
                                <form action="/dashboard/edit-profile?id=<?=$user["id"]?>" method="post" class="mt-4">
                                    <div class="row gx-3 mb-3">
                                        <div class="col-md-6">
                                            <label class="small mb-1" for="inputFirstName">Full name</label>
                                            <input class="form-control" id="fullName" name="fullName" placeholder="Enter your full name..." type="text" value="<?=$fullName?>" disabled/>
                                        </div>

                                        <div class="col-md-6">
                                            <label class="small mb-1" for="inputEmailAddress">Email address</label>
                                            <input class="form-control" id="emailAddress" name="emailAddress" placeholder="Enter your email address..." type="email" value="<?=$email?>" disabled/>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <?php
        include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/footer.phtml';
        ?>
    </div>
</div>
<?php
include $_SERVER["DOCUMENT_ROOT"] . '/templates/layout/scripts.phtml';
?>
</body>
</html>
